Can not set FACTORIO_RCON_PORT & FACTORIO_RCON_PASSWORD
games-on-k8s/docker-factorio pull request #10
Opened 2017-11-18 12:37 UTC by adamcharnock

It seems that setting ``FACTORIO_RCON_PORT`` & ``FACTORIO_RCON_PASSWORD`` actually causes the RCON options to **not** be passed to the server at all. I think this is due to a logic error which this PR addresses.

2017-11-20 02:24 UTC, gtaylor requested changes
One minor tweak. Thanks!

2017-11-20 02:24 UTC, gtaylor commented on entrypoint.sh
> +echo "# RCON port is '${FACTORIO_RCON_PORT}'"
This can be undefined as-is. You'll want to do something like line 29 in breaking that variable out.

2017-11-20 17:54 UTC, adamcharnock commented
Ah yes, thanks @gtaylor. That should be fixed now.

2017-11-21 22:21 UTC, adamcharnock commented
Just fixed another error with this

2019-01-23 20:48 UTC, gtaylor commented
Wow, I am not sure how this got list. Sorry about that! A fix got merged in as part of #15.

2019-01-23 20:48 UTC, closed without merging