Refactored Dockerfile
games-on-k8s/docker-factorio pull request #4
Opened 2017-03-28 12:30 UTC by dgonzalezruiz

This simplifies the syntax and reduces the amount of steps performed.

2017-03-28 21:05 UTC, linki commented
Looks good. But I get this:

```
$ docker build .
...
Step 7/12 : COPY entrypoint.sh gen_config.py factorio.crt /opt
When using COPY with more than one source file, the destination must be a directory and end with a /
```

```
$ docker version
Client:
 Version:      17.03.0-ce
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   60ccb22
 Built:        Thu Feb 23 10:40:59 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      17.03.0-ce
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   3a232c8
 Built:        Tue Feb 28 07:52:04 2017
 OS/Arch:      linux/amd64
 Experimental: true
```

2017-04-09 18:27 UTC, gtaylor requested changes
As @linki noted, one change needed before we can merge this.

2017-04-09 18:27 UTC, gtaylor commented on Dockerfile
> +COPY entrypoint.sh gen_config.py factorio.crt /opt
As noted, there must be a trailing slash here.

2017-05-17 10:22 UTC, HJFinch requested changes

2017-05-17 10:22 UTC, CallMeRoot commented on Dockerfile
If you also fix the Dockerfile to use apt-get instead of apt for python, I could forget my PR #6

2017-05-17 11:06 UTC, dgonzalezruiz commented on Dockerfile
Done! Thanks for the suggestion

2017-05-17 11:17 UTC, dgonzalezruiz commented
I just updated the PR @gtaylor , do you mind having a look? You can close PR #6 after closing this one.

2017-05-17 13:03 UTC, linki commented
I get the following with this:

```console
$ sh make_release.sh 0.15.10
[...]
###
###
# Creating a new map [save.zip]
###
./entrypoint.sh: line 68: /opt/factorio/bin/x64/factorio: No such file or directory
```

2017-05-18 14:43 UTC, gtaylor requested changes
Just the minor flag nit!

2017-05-18 14:43 UTC, gtaylor commented on Dockerfile
The `-y` flag should move back after `apt-get` and before `install`.

2017-05-18 14:43 UTC, gtaylor commented
Also, please squash these commits for me.

2017-05-21 14:05 UTC, dgonzalezruiz commented
Closing this pull request to simplify squash

2017-05-21 14:05 UTC, closed without merging